### ISSUE TITLE
Add interface for SecretsManagerCache

### ISSUE THREAD

**Issue by jonocairns** [aws/aws-secretsmanager-caching-net#14]
Hi there,

Ideally we'd like an interface for this cache to provide the ability to inject mocks or dummy caches for local development. Is it possible to get this done?

Cheers,
Jono

**Comment by joshua-mc** [comment]
This would be extremely useful (necessary?) for unit testing, I was looking for related issues on here as I'm not sure how to go about how to mock this, is there any chance of this being implemented? If not, is there a recommended way on how to mock SecretsManagerCache?

**Comment by joshua-mc** [comment]
https://github.com/aws/aws-secretsmanager-caching-net/pull/16

**Comment by parimaldeshmukh** [comment]
Thank you for your feedback. We have noted this as a feature request.
