### ISSUE TITLE
Caching a transformed value

### ISSUE THREAD

**Issue by jamiewinder** [aws/aws-secretsmanager-caching-net#143]
I often find myself reading a secret and transforming it somehow. Usually converting it from JSON into a POCO. 

As far as I can tell, there is no way to cache this transformed value, just the original string / binary. It seems being able to cache the transformed value would be much more useful.

**Comment by jbct** [comment]
Thanks for the request, jamiewinder. Unfortunately we have no plans to do client processing in the caching library of secret values. One thing you could look into is leveraging the [SecretCacheHook](https://github.com/aws/aws-secretsmanager-caching-net/blob/master/src/Amazon.SecretsManager.Extensions.Caching/ISecretCacheHook.cs) to do some processing in your application.
