### ISSUE TITLE
Revert Microsoft.Extensions.Caching.Memory to 2.2.0

### ISSUE THREAD

**Issue by brianfeucht** [aws/aws-secretsmanager-caching-net#144]
Due to some frustrating dependencies the update to `Microsoft.Extensions.Caching.Memory` causes a breaking [issue](https://github.com/dotnet/aspnetcore/issues/28112) with Kestrel on .NET 4.7.2.  I can go into more details if it is useful but most important bit of information is we are stuck on version `2.2.0` of `Microsoft.Extensions.Primitives` library.  The update made [here](https://github.com/aws/aws-secretsmanager-caching-net/commit/f86f21d018c42d23be3d5aa94290920e8dd1790d#diff-637af0ea5a532d7740e6def15e89891cf7f92887400487e18f1aaac2b7c5782cL26) forced this library to be updated through a transitive dependency.

Consumers of this library should be able to use a newer version by specifying it in their nuget package config without needing to force it here.  

Would you consider reverting this change?

**Comment by jbct** [comment]
Hi @brianfeucht - are you able to take a dependency on v1.0.5?

**Comment by brianfeucht** [comment]
@jbct yes, v1.0.5 will work fine.  Thank you.

**Comment by jbct** [comment]
Thanks for confirming, @brianfeucht. Closing.
