### ISSUE TITLE
SecretsManagerCache to be able to initialize inmemory or distributed cache passed from SecretCacheConfiguration

### ISSUE THREAD

**Issue by hstefanov** [aws/aws-secretsmanager-caching-net#19]
Currently the cache is using inmemory cache, which is not so effective when using in lambda functions, since it is terminated as part of the lambda life. Could you add different cache providers like distributed cache, and flexibility to add any through configuration.

**Comment by parimaldeshmukh** [comment]
Thank you for your feedback. We have noted this as a feature request.

**Comment by avnirambhia2** [comment]
We do not recommend use of distributed caches with AWS Lambda. We suggest you use the sample code at https://github.com/aws/aws-secretsmanager-caching-net/blob/master/README.md. With Lambda container re-use, this code will pull the secret value from cache. To learn more about Lambda container reuse, see https://aws.amazon.com/blogs/compute/container-reuse-in-lambda/.
