### ISSUE TITLE
Assembly is not signed

### ISSUE THREAD

**Issue by paulhickman-a365** [aws/aws-secretsmanager-caching-net#20]
Unlike the rest of the AWS SDK for .Net, this assembly has not been signed with a code signing key.

Therefore, it fails with a runtime error loading the assembly when you try to use it from a signed assembly.

**Comment by parimaldeshmukh** [comment]
Thank you for opening this issue - we are looking into it.

**Comment by simonmarty** [comment]
We published version 1.0.4 with signed assemblies. Please reopen this issue if you keep getting that error.
