### ISSUE TITLE
After upgrading to .NET 6 GetSecretString ocassionally returns null

### ISSUE THREAD

**Issue by dennis3001** [aws/aws-secretsmanager-caching-net#60]
**Description**
We have recently upgraded .NET Web API application that runs on ECS from .NET 3.1 to .NET 6.0
This package  was upgraded from 1.0.3 to 1.0.5.
In the past few days we observed twice that GetSecretString returns null instead of the secret value.
And it keeps returning null until cache TTL expiry. After that correct value is returned again.

**To Reproduce**
Unfortunately steps to reproduce are not known yet

1. 

**Expected behavior**
GetSecretString always returns correct value

**Environment**

.NET version = 6.0
Linux, docker image mcr.microsoft.com/dotnet/sdk:6.0

**Additional context**

**Comment by goyalya** [comment]
Thank you for submitting the request. Could you please share detailed steps to reproduce the issue.
