### ISSUE TITLE
Config provider?

### ISSUE THREAD

**Issue by richardgavel** [aws/aws-secretsmanager-caching-net#7]
Is there a reason this was designed as a custom cache vs a .NET Core configuration provider, similar to the existing provider used to wrap around SSM Parameter Store?

**Comment by lasred** [comment]
yes. We wanted to design this caching library to be compatible with .NET Framework, .NET Standard, and .NET Core. If we designed this as a .NET Core configuration provider, it wouldn't be compatible with the first two.

**Comment by CodeCoded** [comment]
So, if looking for compatibilty, any reason it references .Net Core 2.2 rather than 2.1 given Lambda's native support for 2.1 LTS?
