### ISSUE TITLE
Out of date version references

### ISSUE THREAD

**Issue by ocdavison** [aws/aws-secretsmanager-caching-net#8]
This build can't be used with the latest version of the AWS SDK due to version conflicts. Can you please rebuild and post a new build that supports the current version of the AWS SDK?

![image](https://user-images.githubusercontent.com/3832176/65915606-c708e700-e3a1-11e9-8777-08f467c65b20.png)

**Comment by rstevens011** [comment]
Are you using the caching client or just the regular SDK?  I am able to build AWSSDK.SecretsManager.Caching along side the latest version of the EC2SDK.
