### ISSUE TITLE
Unable to read AWS secret manager from cache

### ISSUE THREAD

**Issue by Prashant15051993** [aws/aws-secretsmanager-caching-net#86]
From CLI we are able to read the secrets for the secret manager and secret manager cache from the console application, now we are running the same on the web-based application from the IIS server, but somehow we are getting timeout error for getting the secret manager cache, it is working fine for getting secret values for the secret manager but failed while getting secret values from the cache.

both are working fine on console-based applications. 

**Expected behavior**
we should be able to fetch secrets from the secrets manager cache.
Created a secret in AWS secret manager and try to access it via the asp.net web application (targetFramework=4.7.2)

**Environment**
AWSSDK.SecretsManager - 3.7.102.19
AWSSDK.SecretsManager.Caching - 1.0.5

.NET version, OS, etc.
targetFramework=4.7.2
Windows Server 2019

**Additional context**

Code 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Amazon;
using Amazon.SecretsManager;
using Amazon.SecretsManager.Model;
using Amazon.SecretsManager.Extensions.Caching;

namespace aws_secret_manager_web
{
    public static class GetSecretValue
    {
        /// <summary>
        /// retrieves a secret named MySecret and sets the TTL cache refresh duration to 24 hours.
        /// </summary>
        public static SecretsManagerCache cache;
        public static string GetCacheData(string secretName)
        {
            return cache.GetSecretString(secretName).Result;           
        }
        private static SecretCacheConfiguration cacheConfiguration = new SecretCacheConfiguration
        {
            CacheItemTTL = 86400000, // retrieves a secret named secretName and sets the TTL cache refresh duration to 24 hours.
            VersionStage = "AWSCURRENT"
        };
        public static string GetSecret(string secretName)
        {
            var config = new AmazonSecretsManagerConfig { RegionEndpoint = RegionEndpoint.EUWest1 };
            IAmazonSecretsManager client = new AmazonSecretsManagerClient(config);

            GetSecretValueRequest request = new GetSecretValueRequest()
            {
                SecretId = secretName,
                VersionStage = "AWSCURRENT" // VersionStage defaults to AWSCURRENT if unspecified.
            };
            GetSecretValueResponse response = null;
            try
            {
                response = client.GetSecretValueAsync(request).Result;
                cache = new SecretsManagerCache(client);
            }
            catch (Exception ex)
            {
                Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
                Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.SystemDiagnostics;
                Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());
            }
            return response?.SecretString;
        }       
    }
}
![RequestTimeOut](https://user-images.githubusercontent.com/130162828/231070832-42683e15-1667-46ea-8bf8-41e6c658b8c9.png)

**Comment by simonmarty** [comment]
```csharp
try
{
    response = client.GetSecretValueAsync(request).Result;
    cache = new SecretsManagerCache(client);
}
```

This section of code does not use the cache to retrieve the secrets, it uses the Secrets Manager Client you created above directly.

Here's the proper way to fetch a secret string through the cache

```csharp
using Amazon.SecretsManager.Extensions.Caching;

internal class Program
{
    private static async Task Main(string[] args)
    {
        var cache = new SecretsManagerCache();

        var secret = await cache.GetSecretString("SecretsManagerTest1");

        if (secret != null)
        {
            Console.WriteLine(secret);
        }
    }
}
```
