### ISSUE TITLE
Version for .Net Core 2.1

### ISSUE THREAD

**Issue by deanmartens** [aws/aws-secretsmanager-caching-net#9]
AWS Lambda officially supports .Net Core 2.1.  Would you make a version that uses 

`<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="2.1.0" />`

instead of 

`<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="2.2.0" />` 

so that I can use it in my Lambda functions?

**Comment by banuprakashbanu** [comment]
We are also getting version conflict error with Microsoft.AspNetCore.App 3.1.0

**Comment by clearwaterstream** [comment]
Guys, AWS Lambda officially supports .NET Core 2.1 LTS, and hopefully soon the newly released 3.1 LTS. Why would you make a package that requires 2.2?? 2.2 will hit EOL very soon, and one would require a custom Lambda runtime (which has its own issue) to use this helper library.

Can you please, going forward, keep in mind that these packages are used by folks running serverless stack, so keep an eye on https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html as you are making the releases / doing testing.

Thanks!!

For now I'll just custom roll some code, hopefully this will be fixed soon.

**Comment by clearwaterstream** [comment]
Also, I foresee Lambda having dual support for .NET Core 2.1 AND 3.1 in the near future, so please consider how you can support both. Thanks!

**Comment by parimaldeshmukh** [comment]
Thank you for opening this issue - we are looking into it.

**Comment by simonmarty** [comment]
[Microsoft.AspNetCore.App](https://www.nuget.org/packages/Microsoft.AspNetCore.App/) has upped their requirement for `Microsoft.Extensions.Caching.Memory` to `2.2.0` on their latest version, closing.
